name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.12.0-beta3

    - name: Initialize Terraform
      run: terraform init

    - name: Format the code
      run: terraform fmt

    - name: Validate the code
      run: terraform validate

    - name: Check the plan
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve
